### ISSUE TITLE
Calimero Installation Problem

### ISSUE THREAD

**Issue by berhankanbur** [Race666/calimero-server#27]
Hello, First of all, I apologize for my bad english.  I have a ABB S/1.2 USB Interface. I'm trying to install calimero on my debian installed OrangePi PC Plus device, but i can't install calimero.

https://michlstechblog.info/blog/eib-knx-knxnet-ip-gateway-with-calimero-server-on-raspberry-pi-orange-pi-pc/

I follow the steps in this blog; 

bash calimero_2.sh usb when i run this command; ''Configure support for USB No supported Hardware detected''  i'm getting to warning.

I don't know how to configure USB. I don't know much about Linux. Please help, I've been trying for a week but I couldn't do it.

**Comment by Race666** [comment]
Could you please execute ```dmesg``` and post the first 20 lines.

**Comment by berhankanbur** [comment]
> Could you please execute `dmesg` and post the first 20 lines.
![Capture](https://user-images.githubusercontent.com/64873540/169791090-56bba532-d901-4835-a7cc-a9e1cbe98c99.PNG)

**Comment by Race666** [comment]
You have got an Xunlong Orange Pi PC Plus. I've tested the script only on an Xunlong Orange Pi PC
You to adjust line 160:
```if [ "$HARDWARE_STRING_OPI" = "Xunlong Orange Pi PC Plus" ]; then```
to recogize your Orange Pi correctly.

**Comment by Race666** [comment]
Ok,nice to hear :-) . Which Image have you installed?

**Comment by berhankanbur** [comment]
> Tamam, bunu duymak güzel :-) . Hangi Image'i kurdunuz? Orange Pi PC için Armbian?

I installed Debian 10 image compiled for Orange Pi PC.

**Comment by Race666** [comment]
Although the Orange Pi PC plus has the same SoC (H3) like Orange Pi PC you cannot use the whole hardware features of the Orange Pi PC plus with the Orange Pi PC image,  because there are different linux kernel DT (devicetree) and overlays. I think the best way is to install Armbian for Orange Pi PC plus and adjust the line 160 of my script as descripted [above](https://github.com/Race666/calimero-server/issues/27#issuecomment-1136228702).  Use a second sd card and if it's not working switch back to the old one.

**Comment by berhankanbur** [comment]
I'll try, but I guess Home Assistant Supervised Armbian is not installed. But for the moment the PC image satisfies all my requests. Thanks again for this super script. It works great!
